export const FETCH_EXPENSES_REQUEST = 'FETCH_EXPENSES_REQUEST';
export const FETCH_EXPENSES_SUCCESS = 'FETCH_EXPENSES_SUCCESS';
export const FETCH_EXPENSES_FAILURE = 'FETCH_EXPENSES_FAILURE';

export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const SET_FILTER_CURRENCY = 'SET_FILTER_CURRENCY';
export const SET_FILTER_START_DATE = 'SET_FILTER_START_DATE';
export const SET_FILTER_END_DATE = 'SET_FILTER_END_DATE';
